# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'gpj-client/package-lock.json'
    - run: cd gpj-client && npm ci
    - run: cd gpj-client && npm run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./gpj-server/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          postgres
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './gpj-server/package-lock.json'
    - run: cd gpj-server && npm ci
    - run: cd gpj-server && npm run migrate
    - run: cd gpj-server && npm run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}